"""Launch curriculum v5 unit definitions.

Each entry: (unit_id, title, description, badge, words_list)
`words_list` includes both vocabulary words and phrase video IDs.
Home-path order is defined in UNIT_ORDER_BY_TITLE.
"""

from __future__ import annotations

# (id, title, description, badge, words)
UNIT_SPECS: list[tuple[str, str, str, str, list[str]]] = [
    ("p1-u01", "Getting Started", "Your first conversation.", "Starter",
     ["hello", "thankyou", "bye", "please", "name", "sorry", "welcome",
      "mynameis", "nicetomeetyou", "howareyou", "imfine", "signslow", "imsorry", "yourewelcome"]),
    ("p1-u02", "Quick Responses", "Yes, no, and when you're stuck.", "Chatty",
     ["yes", "no", "ok", "sure", "alright", "wow", "really",
      "dontknow", "notyet", "signagain", "excuseme", "seeyoulater", "samehere", "havegoodday"]),
    ("p1-u03", "Me & You", "Subject pronouns.", "Subject",
     ["i", "me", "you", "we", "us", "our", "my", "your"]),
    ("p1-u07", "Ask & Answer", "Wh-questions.", "Inquirer",
     ["what", "where", "when", "who", "why", "how", "which",
      "whatisyourname", "whatsthat", "whatdoesthatmean"]),
    ("p1-u06", "Check-ins", "How people feel.", "Mood",
     ["fine", "good", "great", "bad", "happy", "sad", "tired", "angry", "scared", "excited", "worry",
      "imgood", "goodmorning", "goodnight"]),
    ("p1-u73", "Getting Unstuck", "Ask for help and clarity.", "Survival",
     ["again", "wait", "need", "slow", "help", "understand",
      "idontunderstand", "ineedhelp", "canyouhelpme"]),
    ("p1-u05", "Introductions", "Tell someone about yourself.", "Introducer",
     ["person", "people", "myself", "yourself", "sign", "nice", "meet", "introduce"]),
    ("p1-u04", "Mine & Yours", "Possessives and third person.", "Owner",
     ["his", "mine", "he", "they"]),
    ("p1-u21", "Deaf Culture", "The heart of ASL.", "Cultural Bridge",
     ["deaf", "hearing", "hardofhearing", "community", "culture", "identity", "pride", "history",
      "iamdeaf", "iamhearing", "imlearningasl", "signlanguage"]),
    ("p1-u22", "Languages", "Communication tools and ways.", "Linguist",
     ["interpreter", "caption", "hearingaid", "lipread", "gesture", "translate"]),
    ("p1-u15", "Numbers", "Core number signs.", "Counter",
     ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven"]),
    ("p1-u10", "ABCs Part 1", "Letters A through G.", "A-G",
     ["a", "b", "c", "d", "e", "f", "g"]),
    ("p1-u16", "Counting", "Halves, doubles, percents.", "Math",
     ["half", "quarter", "percent", "double", "triple", "hundred"]),
    ("p1-u11", "ABCs Part 2", "Letters H through N.", "H-N",
     ["h", "i", "j", "k", "l", "m", "n"]),
    ("p1-u39", "Days of the Week", "Monday through Sunday.", "Weekly",
     ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]),
    ("p1-u41", "Time", "Hours, weeks, months, years.", "Timekeeper",
     ["day", "week", "month", "year", "hour", "minute", "weekend", "holiday"]),
    ("p1-u40", "When", "Today, yesterday, tomorrow.", "Scheduler",
     ["morning", "afternoon", "night", "today", "yesterday", "tomorrow", "now", "noon", "later", "early"]),
    ("p1-u18", "Family", "Closest people.", "Family",
     ["mother", "father", "sister", "brother", "baby", "child", "family", "parents"]),
    ("p1-u20", "People", "People you meet.", "Networker",
     ["man", "woman", "boy", "girl", "adult", "teenager"]),
    ("p1-u14", "Spelling", "Fingerspell any word.", "Speller",
     ["alphabet", "fingerspell", "letter", "language", "word", "name"]),
    ("p1-u19", "Family Part 2", "Grandparents and relatives.", "Relatives",
     ["grandmother", "grandfather", "aunt", "uncle", "cousin", "niece", "nephew", "twins"]),
    ("p1-u12", "ABCs Part 3", "Letters O through U.", "O-U",
     ["o", "p", "q", "r", "s", "t", "u"]),
    ("p1-u30", "Home", "Where you spend time.", "Homemaker",
     ["home", "house", "kitchen", "bathroom", "bedroom", "livingroom", "basement", "backyard",
      "wherebathroom", "garage"]),
    ("p1-u31", "Furniture", "Things in every room.", "Decorator",
     ["table", "chair", "bed", "couch", "door", "window", "lamp", "clock"]),
    ("p1-u32", "Routine", "Morning routine.", "Fresh",
     ["shower", "toilet", "sink", "soap", "toothbrush", "brush", "comb", "mirror"]),
    ("p1-u33", "Chores", "Keeping the place clean.", "Tidy",
     ["clean", "wash", "cook", "sweep", "vacuum", "washdishes"]),
    ("p1-u24", "Daily Life", "Daily and bodily verbs.", "Daily",
     ["eat", "drink", "sleep", "see", "hear", "feel", "breathe", "smell"]),
    ("p1-u34", "Mealtime", "Breakfast through dinner.", "Mealtime",
     ["breakfast", "lunch", "dinner", "hungry", "full", "delicious"]),
    ("p1-u35", "Fruits", "Fruit basics.", "Fruity",
     ["apple", "banana", "orange", "grapes", "strawberry", "cherry", "pineapple", "lemon"]),
    ("p1-u36", "Vegetables", "Greens and roots.", "Veggie",
     ["tomato", "carrot", "corn", "onion", "potato", "lettuce"]),
    ("p1-u38", "Snacks & Drinks", "Bread, sweets, and sips.", "Sipper",
     ["bread", "pizza", "cake", "chocolate", "water", "coffee", "tea", "juice"]),
    ("p1-u37", "Meat & Dairy", "Proteins and dairy basics.", "Protein",
     ["meat", "fish", "egg", "cheese", "milk", "butter", "bacon", "chicken"]),
    ("p1-u17", "Money", "Dollars, coins, and price.", "Money",
     ["money", "pay", "cost", "price", "1dollar", "5dollars"]),
    ("p1-u09", "How Much", "Amount and intensity.", "Quantifier",
     ["very", "almost", "many", "few", "enough", "more", "less", "really"]),
    ("p1-u27", "Colors", "Bright primary colors.", "Colorist",
     ["red", "blue", "green", "yellow", "orange", "purple", "pink", "brown"]),
    ("p1-u28", "More Colors", "Black, white, and shades.", "Shader",
     ["black", "white", "gray", "gold", "silver", "dark", "light", "bright"]),
    ("p1-u29", "Describing Things", "Size and quality.", "Descriptor",
     ["big", "small", "tall", "hot", "cold", "fast", "hard"]),
    ("p1-u48", "Personality", "How people are.", "Persona",
     ["confident", "humble", "lazy", "stubborn", "curious", "serious", "remember", "forget"]),
    ("p1-u47", "Big Feelings", "Deeper emotions.", "Deep",
     ["bored", "lonely", "jealous", "embarrass", "frustrate", "surprise"]),
    ("p1-u49", "Love", "Connection words.", "Love",
     ["love", "like", "hate", "friend", "hug", "kiss"]),
    ("p1-u08", "And, But, Or", "Connect your sentences.", "Connector",
     ["and", "but", "or", "so", "then", "with", "without", "also", "because", "same", "different", "if"]),
    ("p1-u26", "Doing Things", "Action and helping verbs.", "Doer",
     ["make", "get", "give", "take", "use", "find", "want"]),
    ("p1-u25", "Talking", "Talk and think verbs.", "Talker",
     ["tell", "ask", "talk", "think", "know", "believe"]),
    ("p1-u13", "ABCs Part 4", "Letters V through Z.", "V-Z",
     ["v", "w", "x", "y", "z"]),
    ("p1-u42", "Head & Face", "Eyes, ears, nose, mouth.", "Face",
     ["head", "face", "eyes", "ear", "nose", "mouth", "teeth", "tongue"]),
    ("p1-u43", "Your Body", "Arms, hands, fingers, back.", "Body",
     ["body", "arm", "hands", "finger", "shoulder", "neck", "back", "stomach"]),
    ("p1-u44", "Feeling Sick", "Words for not feeling well.", "Symptoms",
     ["sick", "hurt", "pain", "headache", "cough", "sneeze", "dizzy"]),
    ("p1-u45", "Health", "Staying well.", "Wellness",
     ["health", "exercise", "doctor", "nurse", "hospital", "medicine"]),
    ("p1-u50", "Outfits", "Everyday clothes.", "Daily Wear",
     ["shirt", "pants", "dress", "shoes", "socks", "jacket", "hat", "clothes"]),
    ("p1-u51", "Layers", "Layers and formals.", "Layered",
     ["shorts", "skirt", "sweater", "boots", "gloves", "scarf", "belt", "suit"]),
    ("p1-u52", "Accessories", "Bags, rings, and glasses.", "Accessorized",
     ["glasses", "earring", "necklace", "bracelet", "ring", "backpack", "wallet", "watch"]),
    ("p1-u67", "Party", "Holidays and parties.", "Partygoer",
     ["party", "birthday", "christmas", "halloween", "thanksgiving", "easter"]),
    ("p1-u57", "School", "Education basics.", "Scholar",
     ["school", "class", "student", "teacher", "learn", "study", "read", "write"]),
    ("p1-u58", "Classroom", "Subjects and tools.", "Classroom",
     ["math", "science", "history", "art", "music", "book", "pen", "paper"]),
    ("p1-u59", "Work", "Job life basics.", "Worker",
     ["work", "job", "boss", "lawyer", "engineer", "scientist", "meeting", "retire"]),
    ("p1-u69", "Tech", "Devices and screens.", "Techie",
     ["computer", "phone", "tablet", "laptop", "camera", "tv", "keyboard", "mouse"]),
    ("p1-u70", "Online", "Email and sharing.", "Online",
     ["internet", "email", "text", "download", "upload", "share", "send", "video"]),
    ("p1-u23", "Getting Around", "Movement verbs.", "Mover",
     ["go", "come", "walk", "run", "stop", "turn", "move", "leave"]),
    ("p1-u54", "Directions", "Left, right, here, there.", "Navigator",
     ["here", "there", "left", "right", "up", "down", "near", "far"]),
    ("p1-u55", "Around Town", "Where you go in a day.", "Townie",
     ["school", "hospital", "shop", "park", "restaurant", "hotel", "library", "church"]),
    ("p1-u56", "Commute", "Driving and traffic.", "Commuter",
     ["drive", "ride", "arrive", "travel", "road", "street", "traffic", "commute"]),
    ("p1-u53", "Travel", "Vehicles you use.", "Wheels",
     ["car", "bus", "train", "airplane", "bike", "truck", "motorcycle", "boat"]),
    ("p1-u68", "Countries", "Places on the map.", "Global",
     ["america", "canada", "mexican", "france", "germany", "china", "japan", "italy"]),
    ("p1-u60", "Pets", "Pets and farm.", "Pet Friend",
     ["dog", "cat", "horse", "cow", "pig", "sheep", "rabbit", "duck"]),
    ("p1-u61", "Wild Animals", "Wild and big animals.", "Wild",
     ["lion", "tiger", "elephant", "bear", "wolf", "fox", "eagle", "monkey"]),
    ("p1-u62", "Nature", "Plants, water, sky.", "Nature",
     ["tree", "flower", "mountain", "river", "ocean", "beach", "sun", "moon"]),
    ("p1-u63", "Weather", "Today's forecast.", "Forecaster",
     ["rain", "snow", "wind", "cloud", "lightning", "thunder", "hot", "cold"]),
    ("p1-u64", "Seasons", "Four seasons.", "Seasonal",
     ["spring", "summer", "fall", "winter"]),
    ("p1-u65", "Sports", "Team and solo sports.", "Sporty",
     ["football", "basketball", "baseball", "soccer", "volleyball", "hockey", "tennis", "golf"]),
    ("p1-u66", "Music & Art", "Creative hobbies.", "Creative",
     ["draw", "paint", "sing", "dance", "music", "guitar", "piano", "nicetoseeyou"]),
    ("p1-u71", "Big Ideas", "Possibility and values.", "Thinker",
     ["can", "cannot", "maybe", "important", "right", "wrong", "future", "always"]),
    ("p1-u72", "Useful Expressions", "Everyday ASL idioms.", "Idiom Master",
     ["giveup", "nevermind", "congratulations", "oops",
      "letmesee", "howyousignthat", "onemoretime", "talktoyoulater",
      "blowmind", "allofsudden", "wrapup", "letgo"]),
]

UNIT_ORDER_BY_TITLE: list[str] = [spec[1] for spec in UNIT_SPECS]

PHASE_SEGMENTS: list[tuple[int, str, str]] = [
    (6, "first_conversations", "First Conversations"),
    (8, "about_you", "About You"),
    (10, "deaf_culture", "Deaf Culture"),
    (15, "foundations", "Foundations"),
    (22, "time_family", "Time & Family"),
    (28, "home_daily", "Home & Daily Life"),
    (34, "food_money", "Food & Money"),
    (41, "descriptions_emotions", "Descriptions & Emotions"),
    (44, "sentence_building", "Sentence Building"),
    (45, "alphabet_finish", "Alphabet Finish"),
    (49, "body_health", "Body & Health"),
    (53, "appearance_celebrations", "Appearance & Celebrations"),
    (58, "school_work_tech", "School, Work & Tech"),
    (63, "travel_world", "Travel & World"),
    (66, "animals_nature", "Animals & Nature"),
    (70, "weather_sports_arts", "Weather, Sports & Arts"),
    (72, "big_ideas_expressions", "Big Ideas & Expressions"),
]

PHRASE_IDS: set[str] = {
    "mynameis", "nicetomeetyou", "howareyou", "imfine", "signslow", "imsorry", "yourewelcome",
    "dontknow", "notyet", "signagain", "excuseme", "seeyoulater", "samehere", "havegoodday",
    "whatisyourname", "whatsthat", "whatdoesthatmean", "imgood", "goodmorning", "goodnight",
    "idontunderstand", "ineedhelp", "canyouhelpme", "iamdeaf", "iamhearing", "imlearningasl",
    "wherebathroom", "nicetoseeyou", "letmesee", "howyousignthat", "onemoretime", "talktoyoulater",
    "blowmind", "allofsudden", "wrapup", "letgo",
}

DISPLAY_OVERRIDES: dict[str, str] = {
    "1dollar": "1 Dollar",
    "5dollars": "5 Dollars",
    "allofsudden": "All Of A Sudden",
    "blowmind": "Blow Mind",
    "canyouhelpme": "Can You Help Me",
    "dontknow": "Don't Know",
    "excuseme": "Excuse Me",
    "giveup": "Give Up",
    "goodmorning": "Good Morning",
    "goodnight": "Good Night",
    "hardofhearing": "Hard Of Hearing",
    "havegoodday": "Have A Good Day",
    "hearingaid": "Hearing Aid",
    "howareyou": "How Are You",
    "howyousignthat": "How Do You Sign That",
    "iamdeaf": "I Am Deaf",
    "iamhearing": "I Am Hearing",
    "idontunderstand": "I Don't Understand",
    "imfine": "I'm Fine",
    "imgood": "I'm Good",
    "imlearningasl": "I'm Learning ASL",
    "imsorry": "I'm Sorry",
    "ineedhelp": "I Need Help",
    "letgo": "Let Go",
    "letmesee": "Let Me See",
    "livingroom": "Living Room",
    "mynameis": "My Name Is",
    "nevermind": "Never Mind",
    "nicetomeetyou": "Nice To Meet You",
    "nicetoseeyou": "Nice To See You",
    "notyet": "Not Yet",
    "onemoretime": "One More Time",
    "samehere": "Same Here",
    "seeyoulater": "See You Later",
    "signagain": "Sign Again",
    "signlanguage": "Sign Language",
    "signslow": "Sign Slow",
    "talktoyoulater": "Talk To You Later",
    "thankyou": "Thank You",
    "washdishes": "Wash Dishes",
    "whatdoesthatmean": "What Does That Mean",
    "whatisyourname": "What's Your Name",
    "whatsthat": "What's That",
    "wherebathroom": "Where Is The Bathroom",
    "wrapup": "Wrap Up",
    "yourewelcome": "You're Welcome",
}

# Unit-specific sentence overrides (unit_id -> word_id -> (before, after))
# Remaining words get auto-generated defaults in the generator.
SENTENCE_OVERRIDES: dict[str, dict[str, tuple[str, str]]] = {
    "p1-u01": {
        "hello": ("", ", nice to meet you."),
        "bye": ("", " for now!"),
        "please": ("", ", one moment."),
        "thankyou": ("", " so much!"),
        "sorry": ("", ", my mistake."),
        "welcome": ("You're ", " here."),
        "name": ("My ", " is Max."),
        "mynameis": ("", " — fingerspell name."),
        "nicetomeetyou": ("", ", friend!"),
        "howareyou": ("", " today?"),
        "imfine": ("I am ", ", thanks."),
        "signslow": ("", ", please."),
        "imsorry": ("", ", I forgot."),
        "yourewelcome": ("", ", anytime."),
    },
    "p1-u02": {
        "yes": ("", ", I agree."),
        "no": ("", ", not today."),
        "ok": ("", ", sounds good."),
        "sure": ("", ", count me in."),
        "wow": ("", ", that's amazing!"),
        "really": ("", "? Tell me more."),
        "alright": ("", ", let's begin."),
        "dontknow": ("I ", " yet."),
        "notyet": ("Done? ", "."),
        "signagain": ("", ", please."),
        "excuseme": ("", ", one moment."),
        "seeyoulater": ("", ", friend!"),
        "samehere": ("", ", me too."),
        "havegoodday": ("", ", friend!"),
    },
    "p1-u73": {
        "again": ("", ", please."),
        "wait": ("", " for me."),
        "need": ("I ", " help."),
        "slow": ("Sign ", ", please."),
        "help": ("I ", " now."),
        "understand": ("I ", " now."),
        "idontunderstand": ("", ", repeat please."),
        "ineedhelp": ("", " now."),
        "canyouhelpme": ("", " please?"),
    },
    "p1-u08": {
        "if": ("", " you have time."),
    },
    "p1-u14": {
        "name": ("Fingerspell your ", "."),
    },
    "p1-u21": {
        "signlanguage": ("I love ", "."),
    },
    "p1-u24": {
        "smell": ("I can ", " flowers."),
    },
    "p1-u30": {
        "garage": ("Park in the ", "."),
    },
    "p1-u32": {
        "mirror": ("Look in the ", "."),
    },
    "p1-u37": {
        "chicken": ("Grill the ", " tonight."),
    },
    "p1-u40": {
        "early": ("Wake up ", " today."),
    },
    "p1-u52": {
        "watch": ("Check your ", "."),
    },
    "p1-u68": {
        "italy": ("We visit ", " next."),
    },
    "p1-u69": {
        "mouse": ("Click the ", "."),
    },
    "p1-u70": {
        "video": ("Watch this ", "."),
    },
    "p1-u71": {
        "always": ("I will ", " help."),
    },
}
