#!/usr/bin/env python3
"""Generate ASL/Shared/FilmedSignCatalog.swift from filmmaker video manifests."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


def load_word_ids(scripts_dir: Path) -> list[str]:
    word_ids: set[str] = set()
    for name in ("elijah_videos.json", "victoria_ariel_videos.json"):
        path = scripts_dir / name
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        for video in data.get("videos", []):
            word_id = video.get("wordId")
            if word_id:
                word_ids.add(word_id)
    if not word_ids:
        raise SystemExit("No word IDs found in filmmaker manifests.")
    return sorted(word_ids)


def swift_lines(word_ids: list[str]) -> str:
    chunks: list[str] = []
    line: list[str] = []
    for word_id in word_ids:
        line.append(f'"{word_id}"')
        if len(line) >= 8:
            chunks.append(", ".join(line))
            line = []
    if line:
        chunks.append(", ".join(line))
    body = ",\n        ".join(chunks)
    return f"""// Generated by scripts/generate_filmed_sign_catalog.py — do not hand-edit.
import Foundation

enum FilmedSignCatalog {{
    static let wordIds: Set<String> = [
        {body},
    ]

    static func isFilmed(wordId: String) -> Bool {{
        wordIds.contains(wordId)
    }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "ASL" / "Shared" / "FilmedSignCatalog.swift",
    )
    args = parser.parse_args()

    word_ids = load_word_ids(Path(__file__).resolve().parent)
    args.output.write_text(swift_lines(word_ids), encoding="utf-8")
    print(f"Wrote {len(word_ids)} word IDs to {args.output}")


if __name__ == "__main__":
    main()
