#!/usr/bin/env python3
"""Generate StoneMediaManifest.swift and stone_media_manifest.json from curriculum.json."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

# First ~10 teaching units on path1 (skip reviews/milestones).
BUNDLE_UNIT_IDS = [
    "p1-u01",
    "p1-u02",
    "p1-u03",
    "p1-u73",
    "p1-u06",
    "p1-u05",
    "p1-u22",
]

def load_filmed_ids(repo_root: Path) -> set[str]:
    catalog = repo_root / "ASL" / "Shared" / "FilmedSignCatalog.swift"
    import re

    text = catalog.read_text(encoding="utf-8")
    return set(re.findall(r'"([a-z0-9]+)"', text))


def stone_word_ids(lesson: dict) -> list[str]:
    ids: list[str] = []
    seen: set[str] = set()

    def add(value: str | None) -> None:
        if value and value not in seen:
            seen.add(value)
            ids.append(value)

    for word_id in lesson.get("wordIds", []):
        add(word_id)
    for step in lesson.get("steps", []):
        add(step.get("wordId"))
        add(step.get("answerWordId"))
        add(step.get("comparisonWordId"))
        for key in ("distractorWordIds", "pairWordIds", "sequenceWordIds", "questionWordIds", "choices"):
            for item in step.get(key, []):
                add(item)
    return ids


def teaching_units(curriculum: dict) -> list[dict]:
    units: list[dict] = []
    for path in curriculum.get("paths", []):
        for unit in path.get("units", []):
            if unit.get("isReview") or unit.get("isMilestone"):
                continue
            if not unit.get("lessons"):
                continue
            units.append(unit)
    return units


def build_manifest(curriculum_path: Path, filmed: set[str]) -> dict:
    curriculum = json.loads(curriculum_path.read_text(encoding="utf-8"))
    units = teaching_units(curriculum)

    unit_stones: dict[str, dict[int, list[str]]] = {}
    stone1_bundle_ids: list[str] = []
    seen_stone1: set[str] = set()

    for unit in units:
        unit_id = unit["id"]
        lessons = sorted(unit.get("lessons", []), key=lambda item: item.get("sortOrder", 0))
        unit_stones[unit_id] = {}
        for lesson in lessons:
            stone = int(lesson.get("sortOrder", 0))
            if stone < 1:
                continue
            words = stone_word_ids(lesson)
            unit_stones[unit_id][stone] = words
            if unit_id in BUNDLE_UNIT_IDS and stone == 1:
                for word_id in words:
                    if word_id in filmed and word_id not in seen_stone1:
                        seen_stone1.add(word_id)
                        stone1_bundle_ids.append(word_id)

    return {
        "bundleUnitIds": list(BUNDLE_UNIT_IDS),
        "bundleVideoWordIds": sorted(filmed),
        "stone1VideoWordIds": stone1_bundle_ids,
        "filmedPosterWordIds": sorted(filmed),
        "unitStones": {
            unit_id: {str(stone): words for stone, words in stones.items()}
            for unit_id, stones in unit_stones.items()
        },
    }


def swift_manifest(data: dict) -> str:
    bundle_videos = ", ".join(f'"{w}"' for w in data["bundleVideoWordIds"])
    bundle_units = ", ".join(f'"{u}"' for u in data["bundleUnitIds"])

    unit_entries: list[str] = []
    for unit_id in sorted(data["unitStones"]):
        stone_lines: list[str] = []
        for stone in sorted(data["unitStones"][unit_id], key=int):
            words = data["unitStones"][unit_id][stone]
            word_literal = ", ".join(f'"{w}"' for w in words)
            stone_lines.append(f"            {stone}: [{word_literal}]")
        stones_body = ",\n".join(stone_lines)
        unit_entries.append(f'        "{unit_id}": [\n{stones_body}\n        ]')

    units_body = ",\n".join(unit_entries)

    return f"""// Generated by scripts/generate_stone_media_manifest.py — do not hand-edit.
import Foundation

enum StoneMediaManifest {{
    /// Legacy teaching-unit ids (stone-1 reference; full catalog is bundled).
    static let bundleUnitIds: [String] = [{bundle_units}]

    /// All filmed word IDs shipped as bundled mobile MP4s.
    static let bundleVideoWordIds: Set<String> = [{bundle_videos}]

    /// Stone sortOrder (1–4) → word superset per teaching unit.
    static let wordIdsByUnitStone: [String: [Int: [String]]] = [
{units_body}
    ]

    static func stoneWordIds(unitId: String, stone: Int) -> [String] {{
        wordIdsByUnitStone[unitId]?[stone] ?? []
    }}

    static func isBundledVideo(wordId: String) -> Bool {{
        bundleVideoWordIds.contains(wordId)
    }}

    static func isFilmed(wordId: String) -> Bool {{
        bundleVideoWordIds.contains(wordId)
    }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--curriculum",
        type=Path,
        default=Path(__file__).resolve().parent / "curriculum.json",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    parser.add_argument(
        "--json-out",
        type=Path,
        default=Path(__file__).resolve().parent / "stone_media_manifest.json",
    )
    parser.add_argument(
        "--swift-out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "ASL" / "Shared" / "StoneMediaManifest.swift",
    )
    args = parser.parse_args()

    filmed = load_filmed_ids(args.repo_root)
    manifest = build_manifest(args.curriculum, filmed)
    args.json_out.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    args.swift_out.write_text(swift_manifest(manifest), encoding="utf-8")
    print(
        f"Wrote {args.swift_out} "
        f"({len(manifest['bundleVideoWordIds'])} bundle videos, "
        f"{len(manifest['bundleUnitIds'])} bundle units)"
    )


if __name__ == "__main__":
    main()
